---

dependency:
  name: galaxy
  options:
    role-file: ./requirements.yml
    requirements-file: ./collections.yml
driver:
  name: docker
platforms:
  - name: instance
    image: "geerlingguy/docker-${MOLECULE_DISTRO:-ubuntu2204}-ansible:latest"
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    cgroupns_mode: host
    privileged: true
    pre_build_image: true
provisioner:
  name: ansible
  ansible_args:
    - -vvv
  log: ${MOLECULE_ANSIBLE_LOG:-True}
  env:
    ANSIBLE_VERBOSITY: ${MOLECULE_ANSIBLE_VERBOSITY:-0}
scenario:
  name: default
  destroy_sequence:
    - cleanup
    - destroy
  test_sequence:
    - dependency
    - destroy
    - syntax
    - create
    - prepare
    - converge
#    - verify
    - destroy
verifier:
  name: ansible
